// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.56.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Inte autentiserad." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-my-orders.ts
var list_my_orders_default = defineTool({
  name: "list_my_orders",
  title: "Lista mina best\xE4llningar",
  description: "H\xE4mtar de senaste matbest\xE4llningarna f\xF6r den inloggade Homechef-anv\xE4ndaren (som kund eller kock).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Antal best\xE4llningar att h\xE4mta."),
    status: z.string().optional().describe("Filtrera p\xE5 status, t.ex. pending, confirmed, delivered.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("orders").select("id, status, total_amount, delivery_address, delivery_time, created_at, chef_id, customer_id").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-chefs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_chefs_default = defineTool2({
  name: "search_chefs",
  title: "S\xF6k hemmakockar",
  description: "S\xF6ker godk\xE4nda hemmakockar p\xE5 Homechef efter stad, namn eller specialitet.",
  inputSchema: {
    city: z2.string().optional().describe("Stad att filtrera p\xE5, t.ex. Stockholm."),
    query: z2.string().optional().describe("Fritext som matchar kockens namn eller verksamhetsnamn."),
    limit: z2.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("public_chef_profiles").select("id, full_name, business_name, city, bio, specialties, profile_image_url").limit(limit ?? 10);
    if (city) q = q.ilike("city", `%${city}%`);
    if (query) q = q.or(`full_name.ilike.%${query}%,business_name.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { chefs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-dishes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_dishes_default = defineTool3({
  name: "search_dishes",
  title: "S\xF6k matr\xE4tter",
  description: "S\xF6ker tillg\xE4ngliga matr\xE4tter p\xE5 Homechef efter namn, kategori, pris eller kock.",
  inputSchema: {
    query: z3.string().optional().describe("Fritext som matchar r\xE4ttens namn eller beskrivning."),
    category: z3.string().optional().describe("Kategori, t.ex. husmanskost, vegetariskt."),
    chefId: z3.string().optional().describe("Begr\xE4nsa till en specifik kocks r\xE4tter (UUID)."),
    maxPrice: z3.number().optional().describe("H\xF6gsta pris i kronor."),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, chefId, maxPrice, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("dishes").select("id, name, description, price, category, allergens, preparation_time, chef_id, image_url, available").eq("available", true).limit(limit ?? 10);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.ilike("category", `%${category}%`);
    if (chefId) q = q.eq("chef_id", chefId);
    if (typeof maxPrice === "number") q = q.lte("price", maxPrice);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { dishes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "H\xE4mta min profil",
  description: "H\xE4mtar profil och roller f\xF6r den inloggade Homechef-anv\xE4ndaren.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: profileError }, { data: roles }] = await Promise.all([
      supabase.from("profiles").select("id, full_name, email, phone").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    if (profileError) {
      return { content: [{ type: "text", text: profileError.message }], isError: true };
    }
    const result = { profile, roles: (roles ?? []).map((r) => r.role) };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/update-order-status.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var update_order_status_default = defineTool5({
  name: "update_order_status",
  title: "Uppdatera best\xE4llningsstatus",
  description: "Uppdaterar status p\xE5 en best\xE4llning. Endast till\xE5tet f\xF6r den kock som \xE4ger best\xE4llningen (RLS avg\xF6r).",
  inputSchema: {
    orderId: z4.string().describe("Best\xE4llningens UUID."),
    status: z4.enum(["pending", "confirmed", "preparing", "ready", "delivered", "cancelled"]).describe("Ny status f\xF6r best\xE4llningen.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ orderId, status }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("orders").update({ status }).eq("id", orderId).select("id, status, updated_at");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data || data.length === 0) {
      return {
        content: [{ type: "text", text: "Ingen best\xE4llning uppdaterades \u2013 saknar beh\xF6righet eller fel ID." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0], null, 2) }],
      structuredContent: { order: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rkucenozpmaixfphpiub";
var mcp_default = defineMcp({
  name: "homechef-mcp",
  title: "Homechef",
  version: "0.1.0",
  instructions: "Verktyg f\xF6r Homechef \u2013 Sveriges marknadsplats f\xF6r hemlagad mat. Anv\xE4nd search_chefs och search_dishes f\xF6r att hitta hemmakockar och matr\xE4tter, get_my_profile f\xF6r den inloggade anv\xE4ndaren, list_my_orders f\xF6r best\xE4llningar och update_order_status f\xF6r kockar som vill uppdatera en best\xE4llning.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_chefs_default, search_dishes_default, get_my_profile_default, list_my_orders_default, update_order_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
