// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkucenozpmaixfphpiub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrdWNlbm96cG1haXhmcGhwaXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjQxMjQsImV4cCI6MjA3MTU0MDEyNH0.bvHaR43lcKaWXEwsjVj3wCDSQjeSHlUZuN5gGwzVTRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if localStorage is available
const storage = typeof window !== 'undefined' && window.localStorage ? window.localStorage : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storage,
    persistSession: storage !== undefined,
    autoRefreshToken: storage !== undefined,
  }
});